### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.synapse.experiments#1]
```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/radical/synapse/atoms/atoms.c -o build/temp.linux-x86_64-2.7/src/radical/synapse/atoms/atoms.o

src/radical/synapse/atoms/atoms.c:6:19: fatal error: atoms.h: No such file or directory

 #include "atoms.h"

                   ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/vivek/Research/radical.synapse.experiments/test/bin/python -c "import setuptools, tokenize;__file__='/home/vivek/Research/radical.synapse.experiments/test/build/radical.synapse/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6fQW_M-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vivek/Research/radical.synapse.experiments/test/include/site/python2.7 failed with error code 1 in /home/vivek/Research/radical.synapse.experiments/test/build/radical.synapse
Traceback (most recent call last):
  File "/home/vivek/Research/radical.synapse.experiments/test/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/vivek/Research/radical.synapse.experiments/test/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/vivek/Research/radical.synapse.experiments/test/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 61: ordinal not in range(128)
```

**Comment by andre-merzky** [comment]
Hi Vivek, 

could you please paste the command you used to start the installation?  On what system do you run, and with which python version?

**Comment by vivek-bala** [comment]
I followed the instructions in the readme.

Installation command: pip install radical.synapse==0.10
Python: python/2.7.6

I am running it on my laptop (Ubuntu 14.04).

**Comment by vivek-bala** [comment]
Hi Andre,

Any updates on this ? Should I be trying on some specific machine ?

**Comment by vivek-bala** [comment]
This got fixed with python-dev. 

Also had to comment out https://github.com/radical-cybertools/radical.synapse/blob/master/setup.py#L179. fixdocs file is missing from the bin/ folder.

**Comment by andre-merzky** [comment]
Ah, yes, it needs python-dev.  But I thought that was already required by pymongo, which is a pre-requisite.  Maybe that is different if pymongo is installed as a system package, not via pypi, no idea...

Thanks for the hint with the missing file, I fixed that!
